[translated page] Testing
blitz-js/es.blitzjs.com pull request #17
Opened 2021-04-04 00:18 UTC by UchihaCFC

Aquí me pasa lo mismo que con el title de la página de \<App>, no sé si dejarlo como Testing o cambiarlo a "Pruebas", la verdad es que yo creo que todos estamos más acostumbrados a la palabra testing cuando hablamos de pruebas. Se ha hecho un poco un anglicismo en el mundo dev. ¿Qué pensáis?

2021-04-04 01:01 UTC, JuanM04 requested changes

2021-04-04 01:01 UTC, JuanM04 commented on app/pages/docs/testing.mdx
> +de usar. Para lanzar las pruebas en tu aplicación, tendrás que ejecutar `jest` o `jest --watch` desde el terminal.
"Para lanzar las pruebas en tu aplicación" -> "Para realizar las pruebas de tu aplicación"

2021-04-04 01:01 UTC, JuanM04 commented on app/pages/docs/testing.mdx
> +> [lee la documentación de Jest](https://jestjs.io/docs/en/using-matchers)
¡Ese link tiene una versión en español!
https://jestjs.io/es-ES/docs/using-matchers

2021-04-04 01:01 UTC, JuanM04 commented on app/pages/docs/testing.mdx
> +- Archivos "*.server.test.*".
Usá la tilde la tilde medio chunga: `

2021-04-05 21:18 UTC, UchihaCFC commented
Cambios hechos 👍

2021-04-05 23:26 UTC, JuanM04 approved these changes

2021-04-05 23:26 UTC, merged