Traducción de 'Error Pages'
blitz-js/es.blitzjs.com pull request #39
Opened 2021-09-01 15:14 UTC by Manyfish153

Hola mantenedores, 
vean los cambios a la pagina "Error Pages"
Gracias!

2021-09-02 15:08 UTC, UchihaCFC requested changes
@Manyfish153 buena traducción, mil gracias por tomarte el tiempo :) 

He encontrado algunos pequeños cambios que hacer antes de poder mergear al repo principal, te los he comentado en el review, cualquier duda me dices!

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +title: Paginas de Errores
Páginas de Errores --> Páginas de Error

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +La página 404 puede ser accedida con frequencia tal que Blitz provea una
La página 404 puede ser accedida con frequencia tal que Blitz provea una -> Una página 404 puede ser requerida muy a menudo por lo que Blitz proporciona una

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +Por defecto Blitz proveé una pagina de error 500 cual estilo coincide con
Por defecto Blitz proveé una pagina de error 500 cual estilo coincide con --> Por defecto Blitz **proporciona** una página de error 500 **que coincide con** el estilo de la página 404

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +el estilo de la pagina 404. Esta pagina no es optimizada estaticamente por
Esta pagina no es optimizada estaticamente por lo que permite el reportaje de errores en el servidor. Esta es la razon que 404 y 500 (otros errores) son separados. -->  Esta página no está optimizada estáticamente ya que permite errores del lado del servidor para ser reportados. Esta es la razón por la que 404 y 500 (otros errores)
están separados.

( Cuidado con los acentos/ tildes también )

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +### Customizando La pagina De Error {#customizing-the-error-page}
Customizando La pagina De Error --> Personalización De la Página de Error

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +Errores 500 son manajados por ambos lado del cliente y lado del servidor
Errores 500 son manajados por ambos lado del cliente y lado del servidor -> Los errores 500 se manejan tanto del lado del cliente como del lado del servidor por medio del componente `Error`

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +`app/pages/_error.js` y añade el codigo siguiente:
codigo -> código

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +> `app/pages/_error.js` es solo utilisado en producción. En desarollo,
es solo utilisado en producción. En desarollo, -> es sólo utilizado en producción. En desarrollo,

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +> obtendrá un error con la pila de llamadas para saber donde se originó el
donde -> dónde

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +## componente de límite de error personalizado {#custom-error-boundary-component}
componente de límite de error personalizado  -> Personalizando el Componente Error Boundary Fallback

@JuanM04 cómo te quedaría a ti mejor esto? aquí tengo duda de si es mejor este cambio o mejor otro

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +El valor por defecto `app/pages/_app.tsx` configura un límite de error que
El valor por defecto `app/pages/_app.tsx` configura un límite de error que -> El **archivo** `app/pages/_app.tsx` por defecto  ...

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +detecta errores que ocurren durante el procesamiento, en el lado del
detecta errores que ocurren durante el procesamiento, en el lado del -> captura los errores que ocurren durante el renderizado

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +cliente. Esta voluntad también detecta errores dentro de `useQuery`
Est**o** **~~voluntad~~** también detecta errores dentro de `useQuery`

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +El `RootErrorFallback` es reproducido cuando ocurre un error dentro del
El `RootErrorFallback` es reproducido cuando ocurre un error dentro del -> `RootErrorFallback` se renderiza cuando se produce un error dentro de la

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +procesamiento (render), o una mutación o consulta suspendida. Por defecto:
procesamiento (render), o una mutación o consulta suspendida. Por defecto: ---> renderización ,o una mutación o consulta suspendida. Por defecto:

2021-09-02 15:08 UTC, UchihaCFC commented on app/pages/docs/error-pages.mdx
> +no autorizado para hacer algo. La reserva de error puede manejar eso:
La reserva de error puede manejar eso -> El error fallback puede manejar eso:

2021-09-04 17:21 UTC, Manyfish153 commented on app/pages/docs/error-pages.mdx
> +title: Paginas de Errores
Estas correcto

2021-09-04 17:33 UTC, Manyfish153 commented on app/pages/docs/error-pages.mdx
> +el estilo de la pagina 404. Esta pagina no es optimizada estaticamente por
Muy bien

2021-09-05 02:44 UTC, Manyfish153 commented on app/pages/docs/error-pages.mdx
> +## componente de límite de error personalizado {#custom-error-boundary-component}
Estoy de acuerdo con "Personalizando el Componente `Error Boundary Fallback` "  porque mantiene el  nombre del error en ingles

2022-12-30 14:32 UTC, closed without merging