Homepage
blitz-js/es.blitzjs.com pull request #6
Opened 2021-03-02 23:43 UTC by UchihaCFC

En esta página había bastantes términos coloquiales u otros bastante anglosajones, si podemos revisarlo más de uno mejor para llegar a una convención mejor, porque creo que se repetirán mucho en las páginas siguientes.

2021-03-03 01:05 UTC, JuanM04 requested changes

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                    El Framework FullStack con React
"con" -> "de"

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                almacenarlo en caché en el lado del cliente.
"de tener que hacerlo manualmente desde la API, realizar la búsqueda y almacenarlo en caché en el lado del cliente."
->
"de tener que crear cada ruta API, realizar las peticiones desde el cliente y manejar el caché."

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                      <p>Y puedes publicar tu proyecto en un servidor o sin él.</p>
"en un servidor o sin él"
"en tu servidor o _serverless_"

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                        función, importa e intercambia los datos con una API HTTP generada
"función, importa" -> "función importa"

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                        terceros.
"terceros" -> "por terceros" (o puede que no, lo dejo a tu gusto)

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                    <Feature title="Convención en la configuración">
"Convención en la configuración" -> "Convención > Configuración" (o "sobre")

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                  La comunidad de Blitz - Nuestro aspecto más importante
Podés cambiar el "-" por un ":", eso a gustos. También, considerá usar un _guión largo_ en vez de uno normal (este —)

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                          Código de conducta
"Conducta", con C mayúscula (para mantener un estilo)

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                la base de datos al Frontend
"_End-to-End_, desde la Base de Datos hasta el Navegador" puede resultar más elegante... fijate

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                  proovedor de identidad, incluidos el nombre de usuario y contraseña de tu hosting
"proovedor" -> "proveedor"

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                <FeatureIconTitle icon="typescript" title="Soporte a TypeScript de primera clase">
"Soporte a" --> "Soporte para"

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                  end-to-end y segura por tipos. ¡Todos los tipos son completamente estáticos sin
"es totalmente end-to-end y segura por tipos" -> "está completamente asegurada por _tipos_"

2021-03-03 01:05 UTC, JuanM04 commented on app/pages/index.js
> +                  necesidad de un proceso de generación de tipos por separado!.
~~de tipos~~ y se te escapó un punto luego del signo de exclamación

2021-03-06 15:44 UTC, JuanM04 commented
También recordá cambiar el título y la descripción abajo del todo.
Yo traducí la descripción a esto: "Blitz es un framework fullstack de React hiperproductivo construido sobre Next.js y cuenta con la capa de datos "Zero-API"." (para la página de Idiomas). Si formulás una mejor, decime

2021-03-08 18:39 UTC, UchihaCFC commented
@JuanM04 cambios hechos :)

2021-03-08 19:11 UTC, JuanM04 commented
Increíble, la verdad. No sé por qué, pero tres de los detalles que te marqué aparecían como "mensajes ocultos" en GitHub. Son tres estupideces, pero si le podés echar un ojo, mejor. Si no las encontrás, te las paso de nuevo

2021-03-08 19:33 UTC, UchihaCFC commented
Es cierto, no los había visto, ¡estaban escondidos! 😂. Subí esas tres ahora también, cualquier cosa de me dices

2021-03-08 19:37 UTC, JuanM04 approved these changes

2021-03-08 19:37 UTC, merged